import test from 'node:test';
import assert from 'node:assert/strict';
import {generateKeyPairSync,createVerify,createHash} from 'node:crypto';
import {createPlayBilling,inspectSubscription,inspectCatalog,PREMIUM_PLANS,PLAY_PACKAGE,billingBody} from './play-billing.js';
import {entitlementFor} from './entitlements.js';
const keys=generateKeyPairSync('rsa',{modulusLength:2048});
const creds={type:'service_account',client_email:'billing@icarus-test.iam.gserviceaccount.com',private_key:keys.privateKey.export({type:'pkcs8',format:'pem'})};
const env={GOOGLE_PLAY_SERVICE_ACCOUNT_JSON:JSON.stringify(creds),ICARUS_BILLING_SECRET:'e'.repeat(64),ICARUS_BILLING_MODE:'test',ICARUS_BILLING_TEST_USER_IDS:'owner'};
const timestamp=1801036800000;
const user={id:'owner',email:'owner@example.com'};
class Store {constructor(){this.data={users:[user,{id:'other',email:'other@example.com'}],playPurchases:[]};this.queue=Promise.resolve();}async read(){return structuredClone(this.data);}async update(fn){const p=this.queue.then(()=>fn(this.data));this.queue=p.catch(()=>{});return p;}}
function googlePurchase(binding,updates={}){return {externalAccountIdentifiers:{obfuscatedExternalAccountId:binding},subscriptionState:'SUBSCRIPTION_STATE_ACTIVE',acknowledgementState:'ACKNOWLEDGEMENT_STATE_PENDING',testPurchase:{},lineItems:[{productId:'icarus_pro_monthly',expiryTime:new Date(timestamp+86400000).toISOString(),autoRenewingPlan:{autoRenewEnabled:true},offerDetails:{basePlanId:'monthly'}}],...updates};}
function googleProduct(plan){return {packageName:PLAY_PACKAGE,productId:plan.productId,basePlans:[{basePlanId:plan.period,state:'ACTIVE',autoRenewingBasePlanType:{billingPeriodDuration:plan.period},regionalConfigs:[{regionCode:'US',newSubscriberAvailability:true,price:{currencyCode:'USD',units:String(Math.floor(plan.usdCents/100)),nanos:(plan.usdCents%100)*10000000}}]}]};}
function fixture(overrides={}){const store=new Store(),requests=[];let clock=timestamp;let purchase=null;const config={...env,...overrides};const api=createPlayBilling({store,env:config,now:()=>clock,fetchImpl:async(url,options)=>{requests.push({url,options});assert.equal(options.redirect,'error');assert.ok(options.signal);if(url==='https://oauth2.googleapis.com/token'){const jwt=options.body.get('assertion'),[h,p,s]=jwt.split('.');const verify=createVerify('RSA-SHA256');verify.update(`${h}.${p}`);assert.equal(verify.verify(keys.publicKey,Buffer.from(s,'base64url')),true);assert.equal(JSON.parse(Buffer.from(p,'base64url')).aud,'https://oauth2.googleapis.com/token');return Response.json({access_token:'test-access-token',expires_in:3600});}if(url.endsWith(':acknowledge'))return new Response(null,{status:204});if(url.includes('/purchases/subscriptionsv2/'))return purchase instanceof Response?purchase:Response.json(purchase);const plan=PREMIUM_PLANS.find(p=>url.endsWith('/subscriptions/'+p.productId));assert.ok(plan);return Response.json(googleProduct(plan));}});return {api,store,requests,setPurchase:v=>purchase=v,setClock:v=>clock=v};}

test('billing disabled without credentials and does not contact Google',async()=>{const f=fixture({GOOGLE_PLAY_SERVICE_ACCOUNT_JSON:''});const c=await f.api.configuration(user);assert.equal(c.checkoutEnabled,false);assert.equal(c.configured,false);assert.equal(f.requests.length,0);await assert.rejects(f.api.verify(user,'purchase-token-1'),/billing_not_configured/);});
test('default mode remains disabled even with valid credentials',async()=>{const f=fixture({ICARUS_BILLING_MODE:''});assert.equal((await f.api.configuration(user)).checkoutEnabled,false);});
test('private test backend cannot enable real Play checkout',async()=>{const f=fixture({ICARUS_PRIVATE_TEST:'true',ICARUS_BILLING_MODE:'live'});assert.equal((await f.api.configuration(user)).checkoutEnabled,false);});
test('catalog checks all three products, prices, periods and one active plan',async()=>{const f=fixture();const c=await f.api.configuration(user);assert.equal(c.checkoutEnabled,true);assert.equal(c.plans.length,3);assert.equal(c.plans[1].usdCents,1742);assert.match(c.accountBinding,/^[a-f0-9]{64}$/);assert.equal(f.requests.filter(r=>r.url.includes('oauth2')).length,1);await f.api.configuration(user);assert.equal(f.requests.length,4);});
test('test purchases are available only to designated account IDs',async()=>{const f=fixture();assert.equal((await f.api.configuration({id:'other'})).checkoutEnabled,false);});
test('rejects draft, duplicated, wrong-period, unavailable and wrongly priced base plans',()=>{const plan=PREMIUM_PLANS[0];for(const change of [p=>p.basePlans[0].state='DRAFT',p=>p.basePlans.push(p.basePlans[0]),p=>p.basePlans[0].autoRenewingBasePlanType.billingPeriodDuration='P1Y',p=>p.basePlans[0].regionalConfigs[0].newSubscriberAvailability=false,p=>p.basePlans[0].regionalConfigs[0].price.units='11',p=>p.packageName='other.app']){const p=googleProduct(plan);change(p);assert.throws(()=>inspectCatalog(p,plan));}});
test('valid purchased token is verified, stored encrypted, acknowledged server-side, then grants Premium',async()=>{const f=fixture();f.setPurchase(googlePurchase(f.api.accountBinding(user.id)));const e=await f.api.verify(user,'purchase-token-1');assert.equal(e.premium,true);assert.equal(e.source,'google_play');assert.equal(f.store.data.playPurchases.length,1);assert.ok(!JSON.stringify(f.store.data).includes('purchase-token-1'));assert.equal(f.requests.filter(r=>r.url.endsWith(':acknowledge')).length,1);assert.equal(f.store.data.playPurchases[0].acknowledged,true);});
test('a client cannot grant Premium or use a purchase belonging to another account',async()=>{const f=fixture();f.setPurchase(googlePurchase(f.api.accountBinding('other')));await assert.rejects(f.api.verify(user,'purchase-token-1'),/purchase_account_mismatch/);assert.equal(f.store.data.playPurchases.length,0);});
test('same token verification is idempotent and cross-account replay rejected',async()=>{const f=fixture();f.setPurchase(googlePurchase(f.api.accountBinding(user.id)));await Promise.all([f.api.verify(user,'purchase-token-1'),f.api.verify(user,'purchase-token-1')]);assert.equal(f.store.data.playPurchases.length,1);await assert.rejects(f.api.verify({id:'other'},'purchase-token-1'),/purchase_already_bound/);});
test('test mode rejects real purchases without granting or acknowledging',async()=>{const f=fixture();const p=googlePurchase(f.api.accountBinding(user.id));delete p.testPurchase;f.setPurchase(p);await assert.rejects(f.api.verify(user,'purchase-token-1'),/real_purchase_rejected/);assert.equal(f.store.data.playPurchases.length,0);});
for(const state of ['PENDING','PAUSED','ON_HOLD','EXPIRED','PENDING_PURCHASE_CANCELED'])test(`${state} subscriptions do not grant Premium`,async()=>{const f=fixture();f.setPurchase(googlePurchase(f.api.accountBinding(user.id),{subscriptionState:'SUBSCRIPTION_STATE_'+state}));const e=await f.api.verify(user,'purchase-token-1');assert.equal(e.premium,false);assert.equal(f.requests.some(r=>r.url.endsWith(':acknowledge')),false);});
for(const state of ['ACTIVE','IN_GRACE_PERIOD','CANCELED'])test(`${state} valid paid period retains access`,async()=>{const f=fixture();f.setPurchase(googlePurchase(f.api.accountBinding(user.id),{subscriptionState:'SUBSCRIPTION_STATE_'+state}));assert.equal((await f.api.verify(user,'purchase-token-1')).premium,true);});
test('expired line item, malformed expiry, unsupported product and unknown state fail closed',()=>{const p=googlePurchase('binding');p.lineItems[0].expiryTime=new Date(timestamp-1).toISOString();assert.equal(inspectSubscription(p,'binding',timestamp).eligible,false);p.lineItems[0].expiryTime='bad';assert.throws(()=>inspectSubscription(p,'binding',timestamp));p.lineItems[0].expiryTime=new Date(timestamp+86400000).toISOString();p.lineItems[0].productId='other';assert.throws(()=>inspectSubscription(p,'binding',timestamp));p.lineItems[0].productId='icarus_pro_monthly';p.subscriptionState='UNKNOWN';assert.throws(()=>inspectSubscription(p,'binding',timestamp));});
test('linked replacement invalidates old token and never grants it again',async()=>{const f=fixture();f.setPurchase(googlePurchase(f.api.accountBinding(user.id)));await f.api.verify(user,'purchase-token-old');f.setPurchase(googlePurchase(f.api.accountBinding(user.id),{linkedPurchaseToken:'purchase-token-old'}));await f.api.verify(user,'purchase-token-new');const old=f.store.data.playPurchases.find(p=>p.id===createHash('sha256').update('purchase-token-old').digest('hex'));assert.ok(old.replacedBy);const before=f.requests.length;await f.api.verify(user,'purchase-token-old');assert.equal(f.requests.length,before);});
test('Google revocation clears saved access on revalidation',async()=>{const f=fixture();f.setPurchase(googlePurchase(f.api.accountBinding(user.id)));await f.api.verify(user,'purchase-token-1');f.setClock(timestamp+360000);f.setPurchase(new Response('',{status:410}));assert.equal((await f.api.entitlement(user)).premium,false);});
test('stale entitlement cannot persist indefinitely during an outage',async()=>{const f=fixture();f.setPurchase(googlePurchase(f.api.accountBinding(user.id)));await f.api.verify(user,'purchase-token-1');f.setClock(timestamp+660000);f.setPurchase(new Response('',{status:503}));assert.equal((await f.api.entitlement(user)).premium,false);});
test('account deletion during verification cannot create an orphan entitlement',async()=>{const f=fixture();f.store.data.users=[];f.setPurchase(googlePurchase(f.api.accountBinding(user.id)));await assert.rejects(f.api.verify(user,'purchase-token-1'),/account_no_longer_available/);});
test('anonymous and spoofed RTDN cannot update a purchase',async()=>{const f=fixture();await assert.rejects(f.api.notification('',{message:{data:'e30='}}),/invalid_push_identity/);assert.equal(f.store.data.playPurchases.length,0);});
test('token input and verification abuse are bounded',async()=>{const f=fixture();await assert.rejects(f.api.verify(user,'bad token'),/invalid_purchase_token/);for(let i=0;i<12;i++)f.api.rateLimit(user);assert.throws(()=>f.api.rateLimit(user),/billing_rate_limited/);});
test('body parser rejects oversized input before JSON parsing',async()=>{async function* chunks(){yield Buffer.alloc(65537);}await assert.rejects(billingBody(chunks()),/billing_request_too_large/);});
test('developer grants use immutable IDs, not self-registered email claims',()=>{const e={ICARUS_PREMIUM_GRANT_EMAILS:'owner@example.com',ICARUS_PREMIUM_GRANT_USER_IDS:'verified-owner-id'};assert.equal(entitlementFor({id:'attacker',email:'owner@example.com'},e).premium,false);assert.equal(entitlementFor({id:'verified-owner-id'},e).premium,true);assert.equal(entitlementFor({id:'verified-owner-id'},{}).premium,false);});
